# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"E\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\"H\n\x13RegisterUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"v\n\x14RegisterUserResponse\x12#\n\x0fsuccess_payload\x18\x01 \x01(\x0b\x32\n.auth.User\x12\x15\n\rerror_payload\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\x08\x12\x13\n\x0bstatus_code\x18\x04 \x01(\x05\x32P\n\x0b\x41uthService\x12\x41\n\x08register\x12\x19.auth.RegisterUserRequest\x1a\x1a.auth.RegisterUserResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=20
  _USER._serialized_end=89
  _REGISTERUSERREQUEST._serialized_start=91
  _REGISTERUSERREQUEST._serialized_end=163
  _REGISTERUSERRESPONSE._serialized_start=165
  _REGISTERUSERRESPONSE._serialized_end=283
  _AUTHSERVICE._serialized_start=285
  _AUTHSERVICE._serialized_end=365
# @@protoc_insertion_point(module_scope)
