version: "3.8"
services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: Dockerfile
    image: gateway:latest
    environment:
      AUTH_SVC_ADDRESS: "auth:9999"
      USER_SVC_ADDRESS: "user:9998"
    volumes:
      - .:/service
    networks:
      - microservices
    restart: always
    ports:
      - "8080:8080"
#    healthcheck:
#      test: curl --fail http://localhost:8080 || exit 1
#      interval: 60s
#      retries: 5
#      start_period: 20s
#      timeout: 10s

networks:
  microservices:
    name: microservices
    driver: bridge